# Generated by Django 4.0.3 on 2022-03-22 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='sub_district',
            new_name='subdistrict',
        ),
    ]
